/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ConnectIndexRouteImport } from './routes/connect.index'
import { Route as ConnectRoomIdRouteImport } from './routes/connect.$roomId'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnLessonSlugRouteImport } from './routes/learn.$lessonSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectIndexRoute = ConnectIndexRouteImport.update({
  id: '/connect/',
  path: '/connect/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoomIdRoute = ConnectRoomIdRouteImport.update({
  id: '/connect/$roomId',
  path: '/connect/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnLessonSlugRoute = LearnLessonSlugRouteImport.update({
  id: '/learn/$lessonSlug',
  path: '/learn/$lessonSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/practice': typeof PracticeRoute
  '/connect/$roomId': typeof ConnectRoomIdRoute
  '/learn/$lessonSlug': typeof LearnLessonSlugRoute
  '/connect/': typeof ConnectIndexRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/practice': typeof PracticeRoute
  '/connect/$roomId': typeof ConnectRoomIdRoute
  '/learn/$lessonSlug': typeof LearnLessonSlugRoute
  '/connect': typeof ConnectIndexRoute
  '/learn': typeof LearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/practice': typeof PracticeRoute
  '/connect/$roomId': typeof ConnectRoomIdRoute
  '/learn/$lessonSlug': typeof LearnLessonSlugRoute
  '/connect/': typeof ConnectIndexRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/practice'
    | '/connect/$roomId'
    | '/learn/$lessonSlug'
    | '/connect/'
    | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/practice'
    | '/connect/$roomId'
    | '/learn/$lessonSlug'
    | '/connect'
    | '/learn'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/practice'
    | '/connect/$roomId'
    | '/learn/$lessonSlug'
    | '/connect/'
    | '/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  PracticeRoute: typeof PracticeRoute
  ConnectRoomIdRoute: typeof ConnectRoomIdRoute
  LearnLessonSlugRoute: typeof LearnLessonSlugRoute
  ConnectIndexRoute: typeof ConnectIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/': {
      id: '/connect/'
      path: '/connect'
      fullPath: '/connect/'
      preLoaderRoute: typeof ConnectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/$roomId': {
      id: '/connect/$roomId'
      path: '/connect/$roomId'
      fullPath: '/connect/$roomId'
      preLoaderRoute: typeof ConnectRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$lessonSlug': {
      id: '/learn/$lessonSlug'
      path: '/learn/$lessonSlug'
      fullPath: '/learn/$lessonSlug'
      preLoaderRoute: typeof LearnLessonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  PracticeRoute: PracticeRoute,
  ConnectRoomIdRoute: ConnectRoomIdRoute,
  LearnLessonSlugRoute: LearnLessonSlugRoute,
  ConnectIndexRoute: ConnectIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
