CREATE TABLE public.call_signals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id uuid NOT NULL REFERENCES public.rooms(id) ON DELETE CASCADE,
  sender_id uuid NOT NULL,
  recipient_id uuid NOT NULL,
  signal_type text NOT NULL CHECK (signal_type IN ('offer', 'answer', 'ice')),
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, DELETE ON public.call_signals TO authenticated;
GRANT ALL ON public.call_signals TO service_role;

ALTER TABLE public.call_signals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "room members read call signals"
ON public.call_signals FOR SELECT TO authenticated
USING (
  public.is_room_member(room_id, auth.uid())
  AND (sender_id = auth.uid() OR recipient_id = auth.uid())
);

CREATE POLICY "room members create call signals"
ON public.call_signals FOR INSERT TO authenticated
WITH CHECK (
  sender_id = auth.uid()
  AND recipient_id <> auth.uid()
  AND public.is_room_member(room_id, auth.uid())
  AND public.is_room_member(room_id, recipient_id)
);

CREATE POLICY "senders delete call signals"
ON public.call_signals FOR DELETE TO authenticated
USING (sender_id = auth.uid());

CREATE INDEX call_signals_recipient_room_created_idx
ON public.call_signals (recipient_id, room_id, created_at);

ALTER PUBLICATION supabase_realtime ADD TABLE public.call_signals;